version: "3.4"
services:
    frontend:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: frontend
        command:
            npm run watch-sass
        volumes:
            - .:/code/
            # We do not want node_modules on the host machine, so we create an
            # additional volume for it. It is important this anonymous volume
            # comes after the above bind to work.
            - /code/nodejs/node_modules/
    os2borgerpc-admin:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: os2borgerpc
        command:
            sh -c "python manage.py initialize_database &&
                   gunicorn --reload --timeout 0 --config /code/docker/gunicorn-settings.py os2borgerpc_admin.wsgi"
        volumes:
            - .:/code/
            - ./dev-environment/dev-settings.ini:/user-settings.ini
            - ./dev-environment/system_fixtures:/code/admin_site/system/fixtures/
        depends_on:
            - db
        ports:
            - 9999:9999
        stdin_open: true
        tty: true
        container_name: bpc_admin_site_django
    db:
        image: magentaaps/postgres-os2bos:1-10.14-test
        env_file:
            - dev-environment/db.env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        container_name: bpc_admin_site_db
volumes:
    postgres-data:
