version: "3.4"
services:
    frontend:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: frontend
        command:
            npm run watch-sass
        volumes:
            - .:/code/
            # We do not want node_modules on the host machine, so we create an
            # additional volume for it. It is important this anonymous volume
            # comes after the above bind to work.
            - /code/nodejs/node_modules/
    os2borgerpc-admin:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: os2borgerpc
        command:
            sh -c "python manage.py initialize_database &&
                   gunicorn -b 0.0.0.0:9999 --reload --access-logfile - --timeout 0 os2borgerpc_admin.wsgi"
        volumes:
            - .:/code/
            - ./dev-environment/dev-settings.ini:/user-settings.ini
            - ./dev-environment/system_fixtures:/code/admin_site/system/fixtures/
        depends_on:
            - db
            - postfix
        ports:
            - 9999:9999
        stdin_open: true
        tty: true
    db:
        image: magentaaps/postgres-os2bos:1-10.14-test
        env_file:
            - dev-environment/db.env
        volumes:
            - postgres-data:/var/lib/postgresql/data
    postfix:
        image: catatnight/postfix
        hostname: postfix
        domainname: os2borgerpctest.magenta.example
        environment:
          - maildomain=magenta.example
          - smtp_user=bpc:bpc
volumes:
    postgres-data:
