version: "3.4"
services:
    frontend:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: frontend
        command:
            npm run watch-sass
        volumes:
            - .:/code/
            # We do not want node_modules on the host machine, so we create an
            # additional volume for it. It is important this anonymous volume
            # comes after the above bind to work.
            - /code/nodejs/node_modules/
    os2borgerpc-admin:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: os2borgerpc
        image: os2borgerpcadmin
        command:
            sh -c "python manage.py initialize_database &&
                   python manage.py compilemessages &&
                   gunicorn --reload --reload-extra-file /code/admin_site/locale/da/LC_MESSAGES/django.mo \
                   --reload-extra-file /code/admin_site/locale/da/LC_MESSAGES/djangojs.mo \
                   --reload-extra-file /code/admin_site/locale/sv/LC_MESSAGES/django.mo \
                   --reload-extra-file /code/admin_site/locale/sv/LC_MESSAGES/djangojs.mo \
                   --timeout 0 --config /code/docker/gunicorn-settings.py os2borgerpc_admin.wsgi"
        volumes:
            - .:/code/
            - ./dev-environment/dev-settings.ini:/user-settings.ini
            - ./dev-environment/system_fixtures:/code/admin_site/system/fixtures/
            - ./dev-environment/changelog_fixtures:/code/admin_site/changelog/fixtures/
        depends_on:
            - db
        ports:
            - 9999:9999
        stdin_open: true
        tty: true
        container_name: bpc_admin_site_django
        privileged: true
    cron-service:
        image: os2borgerpcadmin
        volumes:
            - .:/code/
            - ./dev-environment/dev-settings.ini:/user-settings.ini
            - ./dev-environment/system_fixtures:/code/admin_site/system/fixtures/
        command: [ "supercronic", "/crontab" ]
        entrypoint: [ ]
        depends_on:
            - os2borgerpc-admin
    db:
        image: postgres:latest
        restart: always
        environment:
            # Note: These values are only used in the local development environment, so it's not particularly important
            # that they're secure
            POSTGRES_USER: bpc
            POSTGRES_PASSWORD: bpc
        volumes:
            - postgres-data:/var/lib/postgresql/data
        container_name: bpc_admin_site_db
volumes:
    postgres-data:
