# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-30 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('system', '0002_imageversion'), ('system', '0003_auto_20200123_1439')]

    dependencies = [
        ('system', '0001_squashed_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_vers', models.CharField(max_length=7, unique=True)),
                ('rel_date', models.DateField()),
                ('os', models.CharField(max_length=30)),
                ('rel_notes', models.TextField(max_length=350)),
                ('img_path', models.CharField(max_length=200)),
            ],
        ),
    ]
