# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-30 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('system', '0004_site_last_version'), ('system', '0005_auto_20200128_1137')]

    dependencies = [
        ('system', '0002_imageversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='last_version',
            field=models.DateField(blank=True, null=True),
        ),
    ]
