# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-02-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0006_imageversion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageversion",
            name="img_path",
        ),
        migrations.AddField(
            model_name="imageversion",
            name="image_upload",
            field=models.FileField(default="#", upload_to="images"),
        ),
    ]
