# Generated by Django 3.1.4 on 2020-12-10 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system", "0007_auto_20200214_1326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associatedscript",
            name="script",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="associations",
                to="system.script",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="system.configuration"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="package_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="system.packagelist"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="packageinstallinfo",
            name="custom_packages",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="install_infos",
                to="system.custompackages",
            ),
        ),
        migrations.AlterField(
            model_name="packagestatus",
            name="package_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statuses",
                to="system.packagelist",
            ),
        ),
        migrations.AlterField(
            model_name="pc",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="system.configuration"
            ),
        ),
        migrations.AlterField(
            model_name="pc",
            name="custom_packages",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="system.custompackages",
            ),
        ),
        migrations.AlterField(
            model_name="pc",
            name="distribution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="system.distribution"
            ),
        ),
        migrations.AlterField(
            model_name="pc",
            name="package_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="system.packagelist",
            ),
        ),
        migrations.AlterField(
            model_name="pcgroup",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="system.configuration"
            ),
        ),
        migrations.AlterField(
            model_name="pcgroup",
            name="custom_packages",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="system.custompackages"
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="assigned_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="securityproblem",
            name="script",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="security_problems",
                to="system.script",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="system.configuration"
            ),
        ),
    ]
