# Generated by Django 3.1.8 on 2021-05-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20201210_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='custompackages',
            options={'verbose_name_plural': 'Custom packages'},
        ),
    ]
