# Generated by Django 3.1.4 on 2021-04-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20201210_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
