# Generated by Django 3.1.8 on 2021-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_script_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='author'),
        ),
    ]
