# Generated by Django 3.1.8 on 2021-04-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_add_created_and_modified_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='author',
            field=models.CharField(default='', max_length=255, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='script',
            name='author_email',
            field=models.EmailField(default='', max_length=254, verbose_name='author email'),
        ),
    ]
