# Generated by Django 3.1.8 on 2021-05-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_add_script_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
    ]
