# Generated by Django 3.1.8 on 2021-08-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0021_auto_20210809_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="script",
            name="user_created",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=128,
                verbose_name="created by user",
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="user_modified",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=128,
                verbose_name="last modified by user",
            ),
        ),
    ]
