# Generated by Django 3.1.9 on 2021-09-02 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system", "0022_auto_20210809_1500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pc",
            name="mac",
            field=models.CharField(blank=True, max_length=255, verbose_name="MAC"),
        ),
        migrations.AlterField(
            model_name="pc",
            name="uid",
            field=models.CharField(max_length=255, verbose_name="UID"),
        ),
        migrations.AlterField(
            model_name="securityproblem",
            name="alert_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="security_problems",
                to="system.PCGroup",
                verbose_name="alert groups",
            ),
        ),
        migrations.AlterField(
            model_name="securityproblem",
            name="alert_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="security_problems",
                to=settings.AUTH_USER_MODEL,
                verbose_name="alert users",
            ),
        ),
        migrations.AlterField(
            model_name="securityproblem",
            name="level",
            field=models.CharField(
                choices=[
                    ("Critical", "securitylevel:Critical"),
                    ("High", "securitylevel:High"),
                    ("Normal", "securitylevel:Normal"),
                ],
                default="High",
                max_length=10,
                verbose_name="level",
            ),
        ),
    ]
