# Generated by Django 3.1.9 on 2021-09-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("system", "0024_auto_20210902_1240")]

    operations = [
        migrations.RenameField(
            model_name="securityproblem", old_name="script", new_name="security_script"
        ),
        migrations.AlterField(
            model_name="securityproblem",
            name="security_script",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_problems",
                to="system.script",
                verbose_name="security script",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="uid",
            field=models.CharField(max_length=255, verbose_name="UID"),
        ),
        migrations.AlterField(
            model_name="securityproblem",
            name="uid",
            field=models.SlugField(verbose_name="UID"),
        ),
        migrations.AlterField(
            model_name="site",
            name="uid",
            field=models.CharField(max_length=255, unique=True, verbose_name="UID"),
        ),
    ]
