# Generated by Django 3.1.9 on 2021-09-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0025_renaming"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityevent",
            name="pc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_events",
                to="system.pc",
            ),
        ),
    ]
