# Generated by Django 3.1.9 on 2021-09-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_auto_20210920_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='security_alerts',
        ),
    ]
