# Generated by Django 3.1.9 on 2021-09-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_remove_site_security_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='log_output',
            field=models.TextField(blank=True, max_length=128000, verbose_name='log output'),
        ),
    ]
