# Generated by Django 3.1.9 on 2021-10-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0029_auto_20211004_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='activated'),
        ),
    ]
