# Generated by Django 3.1.9 on 2021-11-11 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0034_auto_20211111_1256"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CitizenLogin",
            new_name="Citizen",
        ),
    ]
