# Generated by Django 3.2.9 on 2022-02-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0040_alter_imageversion_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationentry',
            options={'ordering': ['key']},
        ),
    ]
