# Generated by Django 3.2.9 on 2022-02-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0044_alter_imageversion_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='value_type',
            field=models.CharField(choices=[('STRING', 'String'), ('INT', 'Integer'), ('DATE', 'Date'), ('FILE', 'File'), ('BOOLEAN', 'Boolean'), ('PASSWORD', 'Password')], max_length=10, verbose_name='value type'),
        ),
    ]
