# Generated by Django 3.2.12 on 2022-04-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0044_alter_imageversion_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='author',
        ),
        migrations.RemoveField(
            model_name='script',
            name='author_email',
        ),
    ]
