# Generated by Django 3.2.12 on 2022-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0048_rename_ocurred_time_securityevent_occurred_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associatedscriptparameter",
            name="string_value",
            field=models.CharField(blank=True, default="", max_length=4096),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="batchparameter",
            name="string_value",
            field=models.CharField(blank=True, default="", max_length=4096),
            preserve_default=False,
        ),
    ]
