# Generated by Django 3.2.12 on 2022-05-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0051_alter_securityproblem_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcgroup",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=1024, verbose_name="description"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="complete_log",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="note",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
