# Generated by Django 3.2.12 on 2022-06-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0052_auto_20220530_1128"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcgroup",
            name="uid",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
