# Generated by Django 3.2.12 on 2022-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0053_auto_20220602_1522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pc",
            name="uid",
            field=models.CharField(verbose_name="UID", max_length=255, db_index=True),
        ),
    ]
