# Generated by Django 3.2.12 on 2022-06-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0054_alter_pc_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="input",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("STRING", "String"),
                    ("INT", "Integer"),
                    ("DATE", "Date"),
                    ("FILE", "File"),
                    ("BOOLEAN", "Boolean"),
                    ("TIME", "Time"),
                    ("PASSWORD", "Password"),
                ],
                max_length=10,
                verbose_name="value type",
            ),
        ),
    ]
