# Generated by Django 3.2.12 on 2022-07-05 11:46

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0056_auto_20220629_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', markdownx.models.MarkdownxField(verbose_name='content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('version', models.CharField(max_length=255, verbose_name='version')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='system.site')),
                ('tags', models.ManyToManyField(blank=True, related_name='changelogs', to='system.ChangelogTag')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
