# Generated by Django 3.2.14 on 2022-07-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0056_auto_20220629_0922'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pcgroup',
            name='unique_uid_per_group',
        ),
        migrations.RemoveField(
            model_name='pcgroup',
            name='uid',
        ),
    ]
