# Generated by Django 3.2.15 on 2022-09-27 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0059_auto_20220926_1158"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changelog",
            options={"ordering": ["-created"]},
        ),
    ]
