# Generated by Django 3.2.15 on 2022-10-12 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0060_alter_changelog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WakeWeekPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('monday_on', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='monday on')),
                ('monday_off', models.TimeField(blank=True, default=datetime.time(20, 0), null=True, verbose_name='monday off')),
                ('tuesday_on', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='tuesday on')),
                ('tuesday_off', models.TimeField(blank=True, default=datetime.time(20, 0), null=True, verbose_name='tuesday off')),
                ('wednesday_on', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='wednesday on')),
                ('wednesday_off', models.TimeField(blank=True, default=datetime.time(20, 0), null=True, verbose_name='wednesday off')),
                ('thursday_on', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='thursday on')),
                ('thursday_off', models.TimeField(blank=True, default=datetime.time(20, 0), null=True, verbose_name='thursday off')),
                ('friday_on', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='friday on')),
                ('friday_off', models.TimeField(blank=True, default=datetime.time(20, 0), null=True, verbose_name='friday off')),
                ('saturday_on', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='saturday on')),
                ('saturday_off', models.TimeField(blank=True, default=datetime.time(20, 0), null=True, verbose_name='saturday off')),
                ('sunday_on', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='sunday on')),
                ('sunday_off', models.TimeField(blank=True, default=datetime.time(20, 0), null=True, verbose_name='sunday off')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wake_week_plans', to='system.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WakeChangeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('start_datetime', models.DateTimeField(verbose_name='datetime start')),
                ('end_datetime', models.DateTimeField(verbose_name='datetime end')),
                ('on', models.BooleanField(default=False, verbose_name='on')),
                ('wake_week_plans', models.ManyToManyField(related_name='wake_events', to='system.WakeWeekPlan', verbose_name='wake week plans')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='pcgroup',
            name='wake_week_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='system.wakeweekplan'),
        ),
    ]
