# Generated by Django 3.2.14 on 2022-10-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0061_auto_20221012_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Batches'},
        ),
    ]
