# Generated by Django 3.2.15 on 2022-10-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0061_auto_20221012_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='wakeweekplan',
            name='sleep_state',
            field=models.CharField(choices=[('STANDBY', 'sleep_state:Standby'), ('FREEZE', 'sleep_state:Freeze'), ('MEM', 'sleep_state:Mem'), ('OFF', 'sleep_state:Off')], default='OFF', max_length=10),
        ),
    ]
