# Generated by Django 3.2.15 on 2022-10-28 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0063_auto_20221027_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wakechangeevent',
            name='time_end',
            field=models.TimeField(blank=True, default=datetime.time(20, 0), null=True, verbose_name='time end'),
        ),
        migrations.AlterField(
            model_name='wakechangeevent',
            name='time_start',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='time start'),
        ),
    ]
