# Generated by Django 3.2.15 on 2022-10-20 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0063_wakeweekplan_sleep_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wakechangeevent',
            options={'ordering': ['start_date']},
        ),
        migrations.RemoveField(
            model_name='wakechangeevent',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='wakechangeevent',
            name='on',
        ),
        migrations.RemoveField(
            model_name='wakechangeevent',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='wakechangeevent',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 20, 13, 33, 58, 787970), verbose_name='date end'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wakechangeevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='time end'),
        ),
        migrations.AddField(
            model_name='wakechangeevent',
            name='event_type',
            field=models.CharField(choices=[('ALTERED_HOURS', 'event_type:Altered Hours'), ('CLOSED', 'event_type:Closed')], default='ALTERED_HOURS', max_length=15, verbose_name='sleep state'),
        ),
        migrations.AddField(
            model_name='wakechangeevent',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 20, 13, 34, 9, 356142), verbose_name='date start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wakechangeevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='time start'),
        ),
        migrations.AddField(
            model_name='wakeweekplan',
            name='friday_open',
            field=models.BooleanField(default=False, verbose_name='friday open'),
        ),
        migrations.AddField(
            model_name='wakeweekplan',
            name='monday_open',
            field=models.BooleanField(default=False, verbose_name='monday open'),
        ),
        migrations.AddField(
            model_name='wakeweekplan',
            name='saturday_open',
            field=models.BooleanField(default=False, verbose_name='saturday open'),
        ),
        migrations.AddField(
            model_name='wakeweekplan',
            name='sunday_open',
            field=models.BooleanField(default=False, verbose_name='sunday open'),
        ),
        migrations.AddField(
            model_name='wakeweekplan',
            name='thursday_open',
            field=models.BooleanField(default=False, verbose_name='thursday open'),
        ),
        migrations.AddField(
            model_name='wakeweekplan',
            name='tuesday_open',
            field=models.BooleanField(default=False, verbose_name='tuesday open'),
        ),
        migrations.AddField(
            model_name='wakeweekplan',
            name='wednesday_open',
            field=models.BooleanField(default=False, verbose_name='wednesday open'),
        ),
        migrations.AlterField(
            model_name='wakeweekplan',
            name='sleep_state',
            field=models.CharField(choices=[('STANDBY', 'sleep_state:Standby'), ('FREEZE', 'sleep_state:Freeze'), ('MEM', 'sleep_state:Mem'), ('OFF', 'sleep_state:Off')], default='OFF', max_length=10, verbose_name='sleep state'),
        ),
    ]
