# Generated by Django 3.2.15 on 2023-01-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0064_wakechangeevent_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="input",
            name="default_value",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="default value"
            ),
        ),
    ]
