# Generated by Django 3.2.14 on 2022-10-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0065_auto_20221020_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='UID'),
        ),
        migrations.CreateModel(
            name='FeaturePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='UID')),
                ('sites', models.ManyToManyField(blank=True, related_name='feature_permission', to='system.Site', verbose_name='sites with access')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
