# Generated by Django 3.2.15 on 2022-10-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0065_auto_20221020_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wakechangeevent',
            name='event_type',
            field=models.CharField(choices=[('ALTERED_HOURS', 'event_type:Altered Hours'), ('CLOSED', 'event_type:Closed')], default='ALTERED_HOURS', max_length=15, verbose_name='event type'),
        ),
    ]
