# Generated by Django 4.2.1 on 2023-06-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0066_alter_imageversion_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="rerun_asc",
            field=models.BooleanField(
                default=False, verbose_name="Rerun edited associated scripts"
            ),
        ),
    ]
