# Generated by Django 3.2.15 on 2022-10-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0066_alter_wakechangeevent_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wakechangeevent',
            options={'ordering': ['date_start']},
        ),
        migrations.RenameField(
            model_name='wakechangeevent',
            old_name='end_date',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='wakechangeevent',
            old_name='start_date',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='wakechangeevent',
            old_name='end_time',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='wakechangeevent',
            old_name='start_time',
            new_name='time_start',
        ),
        migrations.RemoveField(
            model_name='wakechangeevent',
            name='event_type',
        ),
        migrations.AddField(
            model_name='wakechangeevent',
            name='type',
            field=models.CharField(choices=[('ALTERED_HOURS', 'event_type:Altered Hours'), ('CLOSED', 'event_type:Closed')], default='ALTERED_HOURS', max_length=15, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='wakechangeevent',
            name='wake_week_plans',
            field=models.ManyToManyField(related_name='wake_change_events', to='system.WakeWeekPlan', verbose_name='wake week plans'),
        ),
        migrations.AlterField(
            model_name='wakeweekplan',
            name='friday_open',
            field=models.BooleanField(default=True, verbose_name='friday open'),
        ),
        migrations.AlterField(
            model_name='wakeweekplan',
            name='monday_open',
            field=models.BooleanField(default=True, verbose_name='monday open'),
        ),
        migrations.AlterField(
            model_name='wakeweekplan',
            name='thursday_open',
            field=models.BooleanField(default=True, verbose_name='thursday open'),
        ),
        migrations.AlterField(
            model_name='wakeweekplan',
            name='tuesday_open',
            field=models.BooleanField(default=True, verbose_name='tuesday open'),
        ),
        migrations.AlterField(
            model_name='wakeweekplan',
            name='wednesday_open',
            field=models.BooleanField(default=True, verbose_name='wednesday open'),
        ),
    ]
