# Generated by Django 4.2.1 on 2023-06-13 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0066_alter_imageversion_platform"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="securityproblem",
            name="unique_uid_per_site",
        ),
        migrations.RemoveField(
            model_name="securityproblem",
            name="uid",
        ),
    ]
