# Generated by Django 4.2.1 on 2023-06-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0067_remove_securityproblem_unique_uid_per_site_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="rerun_asc",
            field=models.BooleanField(
                default=False,
                verbose_name="Automatically rerun associated scripts when you update their arguments",
            ),
        ),
    ]
