# Generated by Django 3.2.15 on 2022-10-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0067_auto_20221024_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wakechangeevent',
            name='wake_week_plans',
        ),
        migrations.AddField(
            model_name='wakeweekplan',
            name='wake_change_events',
            field=models.ManyToManyField(related_name='wake_week_plans', to='system.WakeChangeEvent', verbose_name='wake change events'),
        ),
    ]
