# Generated by Django 4.2.1 on 2023-06-28 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system", "0068_site_rerun_asc"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcgroup",
            name="supervisors",
            field=models.ManyToManyField(
                blank=True,
                related_name="pc_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="supervisors",
            ),
        ),
    ]
