# Generated by Django 4.2.1 on 2023-06-27 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0068_site_rerun_asc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changelogcomment",
            name="changelog",
        ),
        migrations.RemoveField(
            model_name="changelogcomment",
            name="parent_comment",
        ),
        migrations.RemoveField(
            model_name="changelogcomment",
            name="user",
        ),
        migrations.DeleteModel(
            name="Changelog",
        ),
        migrations.DeleteModel(
            name="ChangelogComment",
        ),
        migrations.DeleteModel(
            name="ChangelogTag",
        ),
    ]
