# Generated by Django 4.2.1 on 2023-09-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0069_remove_changelogcomment_changelog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="logged_in",
            field=models.BooleanField(default=False),
        ),
    ]
