# Generated by Django 4.2.1 on 2023-09-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0072_eventruleserver_alter_securityevent_problem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="logged_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="site",
            name="cicero_password",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Password for Cicero API",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="cicero_user",
            field=models.CharField(
                blank=True,
                help_text="Necessary for customers who wish to integrate with Cicero login",
                max_length=100,
                verbose_name="Username for Cicero API",
            ),
        ),
    ]
