# Generated by Django 4.2.1 on 2023-10-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0074_apikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="rerun_asc",
            field=models.BooleanField(
                default=True,
                verbose_name="Automatically rerun associated scripts when you update their arguments",
            ),
        ),
    ]
