# Generated by Django 4.2.1 on 2023-10-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0075_alter_site_rerun_asc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="cicero_password",
            new_name="citizen_login_api_password",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="cicero_user",
            new_name="citizen_login_api_user",
        ),
        migrations.AlterField(
            model_name="site",
            name="citizen_login_api_password",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Password for login API (e.g. Cicero)",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="citizen_login_api_user",
            field=models.CharField(
                blank=True,
                help_text="Necessary for customers who wish to authenticate BorgerPC logins through an API (e.g. Cicero)",
                max_length=100,
                verbose_name="Username for login API (e.g. Cicero)",
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="feature_permission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scripts",
                to="system.featurepermission",
            ),
        ),
    ]
