# Generated by Django 4.2.1 on 2023-11-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0077_alter_site_citizen_login_api_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="booking_api_key",
            field=models.CharField(
                blank=True,
                help_text="Necessary for customers who wish to require booking through Easy!Appointments",
                max_length=255,
                verbose_name="API key for Easy!Appointments",
            ),
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(max_length=255, verbose_name="identifier"),
                ),
                ("date", models.DateField(verbose_name="Date of login")),
                ("login_time", models.TimeField(verbose_name="Time of login")),
                (
                    "logout_time",
                    models.TimeField(blank=True, verbose_name="Time of logout"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_log",
                        to="system.site",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "identifier", "login_time"],
            },
        ),
    ]
