# Generated by Django 4.2.1 on 2023-12-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0078_site_booking_api_key_loginlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="booking_api_url",
            field=models.CharField(
                blank=True,
                help_text="Necessary for customers who wish to require booking through Easy!Appointments",
                max_length=255,
                verbose_name="URL domain (including subdomain) for Easy!Appointments",
            ),
        ),
    ]
