# Generated by Django 4.2.1 on 2024-01-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0079_site_booking_api_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventruleserver",
            name="level",
            field=models.CharField(
                choices=[
                    ("Critical", "Critical"),
                    ("High", "High"),
                    ("Normal", "Normal"),
                ],
                default="High",
                max_length=10,
                verbose_name="level",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("SUBMITTED", "Submitted"),
                    ("RUNNING", "Running"),
                    ("FAILED", "Failed"),
                    ("DONE", "Done"),
                    ("RESOLVED", "Restarted"),
                ],
                default="NEW",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("ASSIGNED", "Assigned"),
                    ("RESOLVED", "Resolved"),
                ],
                default="NEW",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="securityproblem",
            name="level",
            field=models.CharField(
                choices=[
                    ("Critical", "Critical"),
                    ("High", "High"),
                    ("Normal", "Normal"),
                ],
                default="High",
                max_length=10,
                verbose_name="level",
            ),
        ),
    ]
