# Generated by Django 4.2.1 on 2024-01-09 11:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0081_country_site_is_testsite_site_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                ("multilang", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="imageversion",
            options={},
        ),
        migrations.RemoveField(
            model_name="imageversion",
            name="platform",
        ),
        migrations.AddField(
            model_name="imageversion",
            name="image_upload_multilang",
            field=models.FileField(
                blank=True, default="#", null=True, upload_to="images"
            ),
        ),
        migrations.AlterField(
            model_name="imageversion",
            name="image_version",
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name="site",
            name="paid_for_access_until",
            field=models.DateField(
                default=datetime.date.today,
                verbose_name="Paid for access until this date",
            ),
        ),
        migrations.AddField(
            model_name="imageversion",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="system.product",
                verbose_name="product",
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="scripts_for_product", to="system.product"
            ),
        ),
    ]
