# Generated by Django 4.2.1 on 2024-02-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0081_country_site_is_testsite_site_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="site",
            name="country",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sites",
                to="system.country",
            ),
        ),
    ]
