# Generated by Django 4.2.9 on 2024-03-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0082_product_alter_imageversion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="citizen_login_api_key",
            field=models.CharField(
                blank=True,
                help_text="Necessary for customers who wish to authenticate BorgerPC logins through an API that requires an API key (e.g. Quria)",
                max_length=255,
                verbose_name="API key for login API (e.g. Quria)",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="isil",
            field=models.CharField(
                blank=True,
                help_text="Necessary for customers who wish to integrate with standard library login",
                max_length=50,
                verbose_name="ISIL/NCIP",
            ),
        ),
        migrations.RenameField(
            model_name="site",
            old_name="isil",
            new_name="agency_id",
        ),
    ]
