# Generated by Django 4.2.1 on 2024-04-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0082_product_alter_imageversion_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="input",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("STRING", "String"),
                    ("INT", "Integer"),
                    ("DATE", "Date"),
                    ("FILE", "File"),
                    ("BOOLEAN", "Boolean"),
                    ("TIME", "Time"),
                    ("PASSWORD", "Password"),
                    ("TEXT_FIELD", "Choices"),
                ],
                max_length=10,
                verbose_name="value type",
            ),
        ),
    ]
