# Generated by Django 4.2.11 on 2024-04-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0084_alter_input_value_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("SUBMITTED", "Submitted"),
                    ("FAILED", "Failed"),
                    ("DONE", "Done"),
                    ("RESOLVED", "Restarted"),
                ],
                default="NEW",
                max_length=10,
            ),
        ),
    ]
