# Generated by Django 4.2.11 on 2024-05-29 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0085_alter_job_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featurepermission",
            name="sites",
        ),
        migrations.RemoveField(
            model_name="site",
            name="country",
        ),
        migrations.RemoveField(
            model_name="site",
            name="is_testsite",
        ),
        migrations.RemoveField(
            model_name="site",
            name="paid_for_access_until",
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="customer name"),
                ),
                (
                    "paid_for_access_until",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Paid for access until this date",
                    ),
                ),
                (
                    "is_test_customer",
                    models.BooleanField(
                        default=False, verbose_name="Is a test customer"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="system.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="featurepermission",
            name="customers",
            field=models.ManyToManyField(
                blank=True,
                related_name="feature_permission",
                to="system.customer",
                verbose_name="customers with access",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sites",
                to="system.customer",
            ),
        ),
    ]
