# Generated by Django 4.2.11 on 2024-06-17 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0085_alter_job_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featurepermission",
            name="sites",
        ),
        migrations.RemoveField(
            model_name="site",
            name="country",
        ),
        migrations.RemoveField(
            model_name="site",
            name="is_testsite",
        ),
        migrations.RemoveField(
            model_name="site",
            name="paid_for_access_until",
        ),
        migrations.AlterField(
            model_name="site",
            name="uid",
            field=models.CharField(
                help_text="This UID is used when registering a PC with the admin site",
                max_length=40,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-z0-9]+\\Z"),
                        "Enter a valid “UID” consisting of lowercase letters, numbers or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="UID",
            ),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="customer name"),
                ),
                (
                    "paid_for_access_until",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Paid for access until this date",
                    ),
                ),
                (
                    "is_test",
                    models.BooleanField(
                        default=False, verbose_name="Is a test customer"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="system.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="featurepermission",
            name="customers",
            field=models.ManyToManyField(
                blank=True,
                related_name="feature_permission",
                to="system.customer",
                verbose_name="customers with access",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sites",
                to="system.customer",
            ),
        ),
    ]
