# Generated by Django 4.2.11 on 2024-06-13 13:57

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0086_remove_featurepermission_sites_remove_site_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="uid",
            field=models.CharField(
                help_text="This UID is used when registrering a PC with the admin site",
                max_length=40,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-z0-9]+\\Z"),
                        "Enter a valid “UID” consisting of lowercase letters, numbers or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="UID",
            ),
        ),
    ]
