# Generated by Django 4.2.11 on 2024-11-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0086_remove_featurepermission_sites_remove_site_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='executable_code',
            field=models.FileField(max_length=255, upload_to='script_uploads', verbose_name='executable code'),
        ),
    ]