# Generated by Django 4.2.30 on 2026-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0087_alter_script_executable_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationentry',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
