# Generated by Django 4.2.11 on 2024-06-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0087_alter_site_uid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="is_test_customer",
            new_name="is_test",
        ),
    ]
