# Generated by Django 4.2.9 on 2024-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changelog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changelog",
            name="author",
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="version",
        ),
        migrations.AddField(
            model_name="changelog",
            name="published",
            field=models.BooleanField(
                default=True, verbose_name="published (visible)"
            ),
        ),
    ]
