# Generated by Django 4.2.9 on 2024-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="hidden user"),
        ),
    ]
